In [1]:
# General
import numpy as np
import pandas as pd
import os
import requests
import urllib.request, json

In [2]:
# Define user
user = os.getlogin()

# Working directories
path_sp  = os.path.join('C:\\Users', 'jfontes', 'Sacramento Area Council of Governments\Regional Monitoring and Reporting - Documents')
path_git = os.path.join('C:\\Users', 'jfontes', 'Documents', 'Projects', 'Regional-Monitoring', 'Indicator_Gen')

# Set file paths
path_config = os.path.join(path_git, 'Python Code', 'Census', 'aa_config')

In [3]:
with urllib.request.urlopen("https://api.census.gov/data/2000/dec/sf1/variables.json") as url:
    dict_dec_2000 = json.load(url)

with urllib.request.urlopen("https://api.census.gov/data/2010/dec/sf1/variables.json") as url:
    dict_dec_2010 = json.load(url)

with urllib.request.urlopen("https://api.census.gov/data/2020/dec/dp/variables.json") as url:
    dict_dec_2020 = json.load(url)

with urllib.request.urlopen("https://api.census.gov/data/2020/dec/dhc/variables.json") as url:
    dict_dhc_2020 = json.load(url)

In [4]:
df_dec_2000 = pd.DataFrame.from_dict(dict_dec_2000['variables']).T.reset_index().rename(columns = {'index':'ID'})
df_dec_2000 = df_dec_2000[['ID', 'label', 'concept', 'predicateType', 'group']]
df_dec_2000['Year'] = 2000
df_dec_2000['sample_type'] = 'DEC_sf1'
df_dec_2000 = df_dec_2000.sort_values(['ID'])
df_dec_2000.head()

,ID,label,concept,predicateType,group,Year,sample_type
3998,AIANHH,American Indian Area/Alaska Native Area/Hawaii...,NaN,NaN,N/A,2000,DEC_sf1
637,AIHHTLI,American Indian Area (Off-Reservation Trust La...,NaN,NaN,N/A,2000,DEC_sf1
2491,AITSCE,American Indian Tribal Subdivision (Census),NaN,NaN,N/A,2000,DEC_sf1
7723,ANRC,Alaska Native Regional Corporation,NaN,NaN,N/A,2000,DEC_sf1
1734,BLKGRP,Census Block Group,NaN,NaN,N/A,2000,DEC_sf1

In [5]:
df_dec_2010 = pd.DataFrame.from_dict(dict_dec_2010['variables']).T.reset_index().rename(columns = {'index':'ID'})
df_dec_2010 = df_dec_2010[['ID', 'label', 'concept', 'predicateType', 'group']]
df_dec_2010['Year'] = 2010
df_dec_2010['sample_type'] = 'DEC_dp'
df_dec_2010 = df_dec_2010.sort_values(['ID'])
df_dec_2010.head()

,ID,label,concept,predicateType,group,Year,sample_type
4372,AIANHH,American Indian Area/Alaska Native Area/Hawaii...,NaN,NaN,N/A,2010,DEC_dp
727,AIHHTLI,American Indian Area (Off-Reservation Trust La...,NaN,NaN,N/A,2010,DEC_dp
2623,AITSCE,American Indian Tribal Subdivision (Census),NaN,NaN,N/A,2010,DEC_dp
8461,ANRC,Alaska Native Regional Corporation,NaN,NaN,N/A,2010,DEC_dp
1798,BLKGRP,Census Block Group,NaN,NaN,N/A,2010,DEC_dp

In [6]:
df_dec_2020 = pd.DataFrame.from_dict(dict_dec_2020['variables']).T.reset_index().rename(columns = {'index':'ID'})
df_dec_2020 = df_dec_2020[['ID', 'label', 'concept', 'predicateType', 'group']]
df_dec_2020['Year'] = 2020
df_dec_2020['sample_type'] = 'DEC_dp'
df_dec_2020 = df_dec_2020.sort_values(['ID'])
df_dec_2020.head()

         ID      label concept predicateType group  Year sample_type
112  AIANHH  Geography     NaN           NaN   N/A  2020      DEC_dp
325    ANRC  Geography     NaN           NaN   N/A  2020      DEC_dp
318    CBSA  Geography     NaN           NaN   N/A  2020      DEC_dp
47       CD  Geography     NaN           NaN   N/A  2020      DEC_dp
76   CNECTA  Geography     NaN           NaN   N/A  2020      DEC_dp

In [7]:
df_dhc_2020 = pd.DataFrame.from_dict(dict_dhc_2020['variables']).T.reset_index().rename(columns = {'index':'ID'})
df_dhc_2020 = df_dhc_2020[['ID', 'label', 'concept', 'predicateType', 'group']]
df_dhc_2020['Year'] = 2020
df_dhc_2020['sample_type'] = 'DEC_dhc'
df_dhc_2020 = df_dhc_2020.sort_values(['ID'])
df_dhc_2020.head()

          ID      label concept predicateType group  Year sample_type
1913  AIANHH  Geography     NaN           NaN   N/A  2020     DEC_dhc
8369  AIHHTL  Geography     NaN           NaN   N/A  2020     DEC_dhc
7024   AIRES  Geography     NaN           NaN   N/A  2020     DEC_dhc
4040    ANRC  Geography     NaN           NaN   N/A  2020     DEC_dhc
837   BLKGRP  Geography     NaN           NaN   N/A  2020     DEC_dhc

In [8]:
df_dec_vars = pd.concat([df_dec_2000, df_dec_2010, df_dec_2020, df_dhc_2020])
df_dec_vars['Label_clean'] = df_dec_vars['label'].str.replace('Estimate!!', '')
df_dec_vars['Label_clean'] = df_dec_vars['Label_clean'].str.replace('!!', ' ')
df_dec_vars['Label_clean'] = df_dec_vars['Label_clean'].str.replace(':', '')
df_dec_vars.head(15)

,ID,label,concept,predicateType,group,Year,sample_type,Label_clean
3998,AIANHH,American Indian Area/Alaska Native Area/Hawaii...,NaN,NaN,N/A,2000,DEC_sf1,American Indian Area/Alaska Native Area/Hawaii...
637,AIHHTLI,American Indian Area (Off-Reservation Trust La...,NaN,NaN,N/A,2000,DEC_sf1,American Indian Area (Off-Reservation Trust La...
2491,AITSCE,American Indian Tribal Subdivision (Census),NaN,NaN,N/A,2000,DEC_sf1,American Indian Tribal Subdivision (Census)
7723,ANRC,Alaska Native Regional Corporation,NaN,NaN,N/A,2000,DEC_sf1,Alaska Native Regional Corporation
1734,BLKGRP,Census Block Group,NaN,NaN,N/A,2000,DEC_sf1,Census Block Group
2411,BLOCK,Census Block,NaN,NaN,N/A,2000,DEC_sf1,Census Block
2302,CD106,Congressional District (106th),NaN,string,N/A,2000,DEC_sf1,Congressional District (106th)
3642,CONCIT,Consolidated City,NaN,NaN,N/A,2000,DEC_sf1,Consolidated City
6612,COUNTY,County (FIPS),NaN,NaN,N/A,2000,DEC_sf1,County (FIPS)
6092,COUSUB,County Subdivision (FIPS),NaN,NaN,N/A,2000,DEC_sf1,County Subdivision (FIPS)
4804,DIVISION,Census Division,NaN,NaN,N/A,2000,DEC_sf1,Census Division
4315,GEOCOMP,GEO_ID Component,NaN,string,N/A,2000,DEC_sf1,GEO_ID Component
7920,GEOVARIANT,Geographic variant,NaN,string,N/A,2000,DEC_sf1,Geographic variant
7898,GEO_ID,Geography,HOUSING UNITS [1];URBAN AND RURAL [6];OCCUPANC...,string,"P027,P026,P013A,P029,P028,P023,P022,P025,P024,...",2000,DEC_sf1,Geography
1053,H001001,Total,HOUSING UNITS [1],int,H001,2000,DEC_sf1,Total

In [9]:
# Export locally just in case url gets moved
df_dec_vars.to_excel(os.path.join(path_config, 'ACS DEC Variables Mapping.xlsx'), index=False)