***

# **CAR Data Scouting**

***

Looking into how usable CAR data is. Did not find anything on the existence of a CAR API, but there are manually downloadable files available online. These files are given by link to a SharePoint Excel file. From there, users can download using browser. The data is in an easily readable format, and would require very minimal cleaning. All data is updated with the last month's data by the third week of the current month. Release schedule is [here](https://carorg.sharepoint.com/:b:/s/CAR-RE-PublicProducts/EQHS3YCtUGFEkM-P4MAs-GgBsbl2PSfPVuOugdtWi1nUXA?e=l5bRe0). 

## [Historical Data](https://www.car.org/marketdata/data/housingdata)

- [Sale of Existing Single Family Homes](https://carorg.sharepoint.com/:x:/s/CAR-RE-PublicProducts/EcA8aeskXYNFtkg1Q2Vtl5QBGCIYEGsnv9DsjR3_tGJ0jQ?e=cgxngp).
This data includes the Percent Change of Sales of Existing Detached Homes across January 1990 to August 2024. The data in the excel does not show for 1990, but does when read in. This data includes every county within California. There are some counties that do not have data, but for the most part it is well documented. 

- [Median Prices of Existing Single Family Homes](https://carorg.sharepoint.com/:x:/s/CAR-RE-PublicProducts/EQr6lTtx5_hCmRawI-XHBkoBt0otrc47S8XAem4f8UAMrw?e=thXabK). This dataset includes the Median Prices of Existing Detached Homes across January 1990 to August 2024. Should be noted that Yuba, Sutter, and Yolo have a lot of missing data for certain years. 

- [Unsold Inventory Index (UII) of Existing Single Family Homes](https://carorg.sharepoint.com/:x:/s/CAR-RE-PublicProducts/EcDFUV4JrPtFofTmqhdiPCoBQ7S1MVK9IFU3A6BE6mt9hA?e=SILk7K). This dataset includes the Unsold Inventory Index of Existing Detached Homes from January 1990 to August 2024.

- [Median Time on Market of Existing Single Family Homes](https://carorg.sharepoint.com/:x:/s/CAR-RE-PublicProducts/EaAOiWPma41ArHBWwYRGQMoBlUe5JMxKixyQ0idvrn7i7Q?e=zu8DEk). This dataset includes the Median Time on Market of Existing Detached Homes from January 1990 to August 2024. The data appears to be in terms of days. Should be noted that the SACOG counties have a good chunk of missing data. Additionally, certain metropolitans like the Bay and LA are clumped together. 

## [City Level Sales and Price Data](https://www.car.org/marketdata/interactive/housingmarketoverview)

This data is sourced by using the interactive, PowerBI dashboard in the browser. The instructions taken from the browser are given here. 

1. Using the drop down filter, find and select the county you are interested in. The tables will then display the current reports available for that county and its cities.

2. Next, click on the icon of your preferred format. 

3. Download and save your report. 

For our sake, we probably only need to use the Historical Data tools, as the report is something we would want to do on our own. 
***

## **Checking Data**

***

In [11]:
import requests

url = 'https://carorg.sharepoint.com/:x:/s/CAR-RE-PublicProducts/EcA8aeskXYNFtkg1Q2Vtl5QBGCIYEGsnv9DsjR3_tGJ0jQ?rtime=8EG4X8fZ3Eg.xlsx'

# Send a GET request to fetch the file content
response = requests.get(url)

# Print the first 500 characters of the response to check its type
print(response.text[:500])

# Check the status code
print(f"Status code: {response.status_code}")

<!DOCTYPE html>
<html lang="en-us" dir="ltr" class="ms-isBot">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta
		name="viewport"
		content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"
	/>
	<meta name="robots" content="noindex" />
	<link
					href='https://res-1.cdn.office.net/wise/owl/owl.slim.29c9352f088f35baee16.js'
					rel='preload'
					integrity='sha384-ZyB3NyMFoWO8aoyle3ek/RSEj0mUSC+d+YgMXF40SdqWjd4
Status code: 200

In [104]:
from requests.auth import HTTPBasicAuth

url = 'https://carorg.sharepoint.com/:x:/s/CAR-RE-PublicProducts/EcA8aeskXYNFtkg1Q2Vtl5QBGCIYEGsnv9DsjR3_tGJ0jQ?rtime=8EG4X8fZ3Eg.xls'

username = 'jchoy'
pw = 'pokeman1!'

resp = requests.get(url, auth=HTTPBasicAuth(username, pw))

output = open('test.xlsx', 'wb')

output.write(resp.content)
output.close()

In [103]:
# Perform the GET request with HTTP basic authentication
resp = requests.get(url, auth=HTTPBasicAuth(username, pw))

# Check if the request was successful (status code 200)
if resp.status_code == 200:
    # Write the downloaded content to a file
    with open('test.xlsx', 'wb') as output:
        output.write(resp.content)
    print('File downloaded successfully.')
else:
    print(f'Failed to download the file. Status code: {resp.status_code}')

File downloaded successfully.

In [106]:
content_type = resp.headers.get('Content-Type')

if resp.status_code == 200:
    if 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' in content_type:
        # Write the downloaded content to a file
        with open('test.xlsx', 'wb') as output:
            output.write(resp.content)
        print('File downloaded successfully.')
    else:
        print(f'Unexpected content type: {content_type}')
        print('Response might be an HTML page or error message.')
        # Optional: Print part of the response content for debugging
        print(resp.text[:500])  # Print first 500 characters of the response
else:
    print(f'Failed to download the file. Status code: {resp.status_code}')

Unexpected content type: text/html; charset=utf-8
Response might be an HTML page or error message.

<!DOCTYPE html>
<html lang="en-us" dir="ltr" class="ms-isBot">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta
		name="viewport"
		content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"
	/>
	<meta name="robots" content="noindex" />
	<link
					href='https://res-1.cdn.office.net/wise/owl/owl.slim.29c9352f088f35baee16.js'
					rel='preload'
					integrity='sha384-ZyB3NyMFoWO8aoyle3ek/RSEj0mUSC+d+YgMXF40SdqWjd4

In [117]:
import requests
from requests_ntlm3 import HttpNtlmAuth

auth = HttpNtlmAuth(username, pw)

myfile = requests.get(url, auth=auth)

open('test.xlsx', 'wb').write(myfile.content)

ModuleNotFoundError: No module named 'requests.packages.urllib3.packages'

In [91]:
import pandas as pd
import os
import requests
from requests_ntlm import HttpNtlmAuth
from io import BytesIO
import plotly.express as px

In [118]:
s_url = 'https://fred.stlouisfed.org/graph/fredgraph.csv?cosd=1990-01-01&coed=2040-01-01&id=CPIAUCSL' 
df = pd.read_csv(s_url)

In [119]:
df

           DATE  CPIAUCSL
0    1990-01-01   127.500
1    1990-02-01   128.000
2    1990-03-01   128.600
3    1990-04-01   128.900
4    1990-05-01   129.100
..          ...       ...
411  2024-04-01   313.207
412  2024-05-01   313.225
413  2024-06-01   313.049
414  2024-07-01   313.534
415  2024-08-01   314.121

[416 rows x 2 columns]

In [150]:
sacog = ['El Dorado', 'Yuba', 'Sacramento', 'Sutter', 'Placer', 'Yolo']

pop_5 = pd.read_csv("C:\\Users\\jchoy\\Sacramento Area Council of Governments\\Regional Monitoring and Reporting - Documents\\Process Revamp\\Task 8. Reproduce Progress Report indicators\\Indicator Data\\DOF Data\\Pop_5\\Pop_5_DOF_Counties.csv")

In [152]:
# Extracting the counties from pop_5. 
# Making a mapping of MPO as a key, and the counties as values.

locs = pop_5.groupby('MPO')['County'].unique().reset_index()

area_dict = dict(zip(locs['MPO'], locs['County']))

county_to_mpo = {county: mpo for mpo, counties in area_dict.items() for county in counties}

***

In [72]:
# staying on my downloads cuz i dont want to import into Git

# Percent Changes file

percent_change = pd.read_excel("C:\\Users\\jchoy\\Downloads\\PercentChangeofSalesofExistingDetachedHomesHistoricalData.xlsx", skiprows=7)
display(percent_change.head(5))

,Mon-Yr,CA*,Alameda,Amador,Butte,Calaveras,Contra-Costa,Del Norte,El Dorado,Fresno,...,Yuba,Unnamed: 55,Condo,LA Metro,Central Coast,Central Valley,Far North,Inland Empire,S.F. Bay Area,SoCal
0,1990-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1990-02-01,-0.017694,NaN,NaN,-0.677966,NaN,-0.065972,NaN,NaN,0.163366,...,NaN,NaN,NaN,-0.039812,-0.159167,NaN,NaN,0.018440,-0.148050,-0.033542
2,1990-03-01,-0.110365,0.580214,NaN,0.263158,NaN,0.780669,NaN,NaN,0.093617,...,NaN,NaN,NaN,0.231572,0.402216,NaN,NaN,0.321478,0.321699,0.247169
3,1990-04-01,-0.054121,-0.011844,NaN,-0.375000,NaN,-0.066806,NaN,NaN,0.159533,...,NaN,NaN,NaN,-0.042863,-0.061394,NaN,NaN,0.034395,0.011665,-0.053895
4,1990-05-01,-0.036446,0.085616,NaN,0.533333,NaN,-0.040268,NaN,NaN,0.127517,...,NaN,NaN,NaN,0.173871,-0.003605,NaN,NaN,0.026416,0.009031,0.164060

In [73]:
percent_long = percent_change.melt(id_vars=['Mon-Yr'], var_name='County', value_name='Percent Change')

# Need to do this for Contra Costa
percent_long['County'] = percent_long['County'].replace('-', ' ', regex=True)

In [74]:
percent_long['MPO'] = percent_long['County'].map(county_to_mpo)

percent_long = percent_long.dropna()

# Find what vcounties are giving NAs for MPO
# percent_long[percent_long['MPO'].isna()]['County'].unique()

In [80]:
# Just SACOG

# sacog_percent = percent_change.loc[:,percent_change.columns[:1].tolist() + sacog]
# display(sacog_percent.tail(5))

# sacog_percent_long = sacog_percent.melt(id_vars=['Mon-Yr'], var_name='County', value_name='Percent Change')

***

In [84]:
# Median Prices

median_prices = pd.read_excel("C:\\Users\\jchoy\\Downloads\\MedianPricesofExistingDetachedHomesHistoricalData.xlsx", skiprows = 7)

median_long = median_prices.melt(id_vars=['Mon-Yr'], var_name='County', value_name='Median Price')

# Need to do this for Contra Costa
median_long['County'] = median_long['County'].replace('-', ' ', regex=True)

median_long['MPO'] = median_long['County'].map(county_to_mpo)

median_long = median_long.dropna()

# # SACOG

# sacog_median = median_prices.loc[:,median_prices.columns[:1].tolist() + sacog]

# sacog_median_long = sacog_median.melt(id_vars=['Mon-Yr'], var_name='County', value_name='Median Price')

***

In [85]:
# Unsold Inventory Index

inventory_index = pd.read_excel("C:\\Users\\jchoy\\Downloads\\UnsoldInventoryIndexofExistingDetachedHomesHistoricalData.xlsx", skiprows = 12)

index_long = inventory_index.melt(id_vars=['Mon-Yr'], var_name='County', value_name='Index')

# Need to do this for Contra Costa
index_long['County'] = index_long['County'].replace('-', ' ', regex=True)

# Use the mapping to create the MPO column based off of county
index_long['MPO'] = index_long['County'].map(county_to_mpo)

index_long = index_long.dropna()


# sacog_index = inventory_index.loc[:,inventory_index.columns[:1].tolist() + sacog]
# display(sacog_index.tail(5))

# sacog_index_long = sacog_index.melt(id_vars=['Mon-Yr'], var_name='County', value_name='Index')

In [86]:
# Time on Market

market_time = pd.read_excel("C:\\Users\\jchoy\\Downloads\\MedianTimeonMarketofExistingDetachedHomesHistoricalData.xlsx", skiprows = 3)

market_long = market_time.melt(id_vars=['Mon-Yr'], var_name='County', value_name='Market Time')

# Need to do this for Contra Costa
market_long['County'] = market_long['County'].replace('-', ' ', regex=True)

market_long['MPO'] = market_long['County'].map(county_to_mpo)

market_long = market_long.dropna()

# sacog_market = market_time.loc[:,market_time.columns[:1].tolist() + sacog]
# display(sacog_market.tail(5))

# sacog_market_long = sacog_market.melt(id_vars=['Mon-Yr'], var_name='County', value_name='Market Time')

In [147]:
# Let's join all of these dataframes together

full_merged = percent_long.merge(index_long, on=['Mon-Yr', 'County', 'MPO']).merge(market_long, on=['Mon-Yr', 'County', 'MPO']).merge(median_long, on=['Mon-Yr', 'County', 'MPO'])

# sacog_merged = sacog_percent_long.merge(sacog_index_long, on=['Mon-Yr', 'County']).merge(sacog_market_long, on=['Mon-Yr', 'County']).merge(sacog_median_long, on=['Mon-Yr', 'County'])

# # Plot all counties
# fig = px.line(sacog_merged, x='Mon-Yr', y='Percent Change', color='County', facet_col='County', template='plotly_white',
#                facet_col_wrap=2, title='Percent Change of Sales for Existing Detached Homes by SACOG County',
#                  labels={
#                      "Percent Change": "Percent Change"
#                  })

# fig.update_layout(yaxis_title = None)

# fig.show()

In [200]:
# Need to average each county by combining the median prices for the years

weight_meds = full_merged
weight_meds['Year'] = weight_meds['Mon-Yr'].dt.year

weight_meds = weight_meds.groupby(['Year', 'County', 'MPO']).agg(
    median_price=('Median Price', 'median')
).reset_index()

In [217]:
# Merging on year, county, and MPO
# Weighing housing cost for future calcs
# Calc total weighted cost and total population per group
# Calc the population weighted average housing cost for each grouping of (Year, County, MPO)

df_weight = pd.merge(weight_meds, pop_5, on=['County', 'Year', 'MPO'])

df_weight['Weighted Price'] = df_weight['median_price'] * df_weight['Population']

df_grouped = df_weight.groupby(['County', 'Year', 'MPO']).apply(
    lambda x: pd.Series({
        'Weighted Avg Price': x['Weighted Price'].sum() / x['Population'].sum()
    })
).reset_index()

display(df_grouped[df_grouped['MPO']=='SACOG'])

C:\Users\jchoy\AppData\Local\Temp\ipykernel_10520\4272996556.py:10: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

        County  Year    MPO  Weighted Avg Price
97   El Dorado  2010  SACOG       290150.712121
98   El Dorado  2011  SACOG       278228.602083
99   El Dorado  2012  SACOG       276810.000000
100  El Dorado  2013  SACOG       343210.000000
101  El Dorado  2014  SACOG       373595.000000
..         ...   ...    ...                 ...
835       Yuba  2020  SACOG       330675.000000
836       Yuba  2021  SACOG       409950.000000
837       Yuba  2022  SACOG       431250.000000
838       Yuba  2023  SACOG       433250.000000
839       Yuba  2024  SACOG       447375.000000

[87 rows x 4 columns]

In [215]:
# Weighting the MPOs by county and 

merged_df = pd.merge(weight_meds, pop_5, on=['County', 'Year', 'MPO'])

merged_df['Weighted Price'] = merged_df['median_price'] * merged_df['Population']

weighted_avg_county_df = merged_df.groupby(['County', 'Year', 'MPO']).apply(
    lambda x: pd.Series({
        'Weighted Avg Price': x['Weighted Price'].sum() / x['Population'].sum()
    })
).reset_index()

display(weighted_avg_county_df)

C:\Users\jchoy\AppData\Local\Temp\ipykernel_10520\1961309554.py:7: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

      County  Year    MPO  Weighted Avg Price
0    Alameda  2000    MTC            371064.0
1    Alameda  2001    MTC            397959.5
2    Alameda  2002    MTC            452735.0
3    Alameda  2007    MTC            658420.0
4    Alameda  2008    MTC            527445.0
..       ...   ...    ...                 ...
835     Yuba  2020  SACOG            330675.0
836     Yuba  2021  SACOG            409950.0
837     Yuba  2022  SACOG            431250.0
838     Yuba  2023  SACOG            433250.0
839     Yuba  2024  SACOG            447375.0

[840 rows x 4 columns]

In [226]:
display(weighted_avg_county_df[weighted_avg_county_df['County'] == 'Alameda'])

In [ ]:
# Mon to Year
# County to MPO
# Here we weight by something
# Sold houses, pop

In [155]:
# Median Price

fig = px.line(full_merged, x='Mon-Yr', y='Median Price', color='County',  template='plotly_white',
               facet_col_wrap=2, title='Median Prices of Existing Detached Homes by MPOs',
                 labels={
                     "Median Price": "Price"
                 })

fig.update_layout(yaxis_title = None)

fig.show()

In [170]:
# aggregating these so that we can graph the MPOs

# needs to be float
full_merged['Market Time'] = pd.to_numeric(full_merged['Market Time'], errors='coerce')

mpo_frame = full_merged.groupby(['MPO', 'Mon-Yr'], as_index=False).agg({
    'Percent Change': 'mean',
    'Index': 'mean',
    'Market Time': 'mean',
    'Median Price': 'median' # not going to actually plot this one tho, use other frame for it
})

In [184]:
# Median Time on Market plot

fig = px.line(mpo_frame, 
              x='Mon-Yr', 
              y='Market Time', 
              color='MPO', 
              facet_col='MPO', 
              template='plotly_white',
              facet_col_wrap=2, title='Median Time on Market of Existing Detached Homes by MPOs',
              labels={"Market Time": "Time in Days"})

fig.update_layout(
    yaxis_title=None,
    showlegend=True            
)

fig.for_each_annotation(lambda a: a.update(text=''))
fig.for_each_yaxis(lambda y: y.update(title_text=''))


fig.show()

In [183]:
fig = px.line(mpo_frame, 
              x='Mon-Yr', 
              y='Index', 
              color='MPO', 
              facet_col='MPO', 
              template='plotly_white',
              facet_col_wrap=2, 
              title='Unsold Inventory Index of Existing Detached Homes by MPOs')

fig.update_layout(
    yaxis_title=None,
    showlegend=True            
)

fig.for_each_annotation(lambda a: a.update(text=''))
fig.for_each_yaxis(lambda y: y.update(title_text=''))


fig.show()

In [179]:
# Might want to do this one with year diffs instead

fig = px.line(mpo_frame, x='Mon-Yr', y="Percent Change", color='MPO', facet_col = 'MPO', template='plotly_white',
               facet_col_wrap=2, title='Monthly Percent Changes of Sales for Existing Detached Homes by MPOs',
                 labels={
                     "Percent Change": "Percent Diff"
                 })

fig.update_layout(yaxis_title = None)

fig.show()

In [219]:
df_grouped

      County  Year    MPO  Weighted Avg Price
0    Alameda  2000    MTC            371064.0
1    Alameda  2001    MTC            397959.5
2    Alameda  2002    MTC            452735.0
3    Alameda  2007    MTC            658420.0
4    Alameda  2008    MTC            527445.0
..       ...   ...    ...                 ...
835     Yuba  2020  SACOG            330675.0
836     Yuba  2021  SACOG            409950.0
837     Yuba  2022  SACOG            431250.0
838     Yuba  2023  SACOG            433250.0
839     Yuba  2024  SACOG            447375.0

[840 rows x 4 columns]

In [223]:
# only looking at MPOs

price_mpo =  merged_df.groupby(['Year', 'MPO']).apply(
    lambda x: pd.Series({
        'Weighted Avg Price': x['Weighted Price'].sum() / x['Population'].sum()
    })
).reset_index()

display(weighted_avg_county_df)

fig = px.line(price_mpo, x='Year', y="Weighted Avg Price", color='MPO', facet_col = 'MPO', template='plotly_white',
               facet_col_wrap=2, title='Monthly Percent Changes of Sales for Existing Detached Homes by MPOs',
                 labels={
                     "Percent Change": "Percent Diff"
                 })

fig.update_layout(yaxis_title = None)

fig.show()

C:\Users\jchoy\AppData\Local\Temp\ipykernel_10520\1703530134.py:3: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

      County  Year    MPO  Weighted Avg Price
0    Alameda  2000    MTC            371064.0
1    Alameda  2001    MTC            397959.5
2    Alameda  2002    MTC            452735.0
3    Alameda  2007    MTC            658420.0
4    Alameda  2008    MTC            527445.0
..       ...   ...    ...                 ...
835     Yuba  2020  SACOG            330675.0
836     Yuba  2021  SACOG            409950.0
837     Yuba  2022  SACOG            431250.0
838     Yuba  2023  SACOG            433250.0
839     Yuba  2024  SACOG            447375.0

[840 rows x 4 columns]

In [174]:
mpo_frame

        MPO     Mon-Yr  Percent Change  Index  Market Time  Median Price
0     CVCOG 1990-01-01             NaN   5.90    46.201613       85892.0
1     CVCOG 1990-02-01       -0.195556   7.60    58.187500       80294.0
2     CVCOG 1990-03-01        0.187845   6.10    61.467742       87758.0
3     CVCOG 1990-04-01        0.255814   4.90    43.742424       80323.0
4     CVCOG 1990-05-01        0.177778   4.10    50.078947       86562.0
...     ...        ...             ...    ...          ...           ...
1948   SCAG 2024-04-01        0.041963   2.84    22.600000      650000.0
1949   SCAG 2024-05-01        0.110473   2.62    21.600000      650000.0
1950   SCAG 2024-06-01       -0.112487   2.98    22.000000      643500.0
1951   SCAG 2024-07-01       -0.002870   3.16    25.400000      650000.0
1952   SCAG 2024-08-01        0.004073   3.36    24.000000      630000.0

[1953 rows x 6 columns]

In [ ]:
# import population metric from dof. for each county
# compare mpo levels and see diffs btwn grps

In [65]:
# # Market time plot sacog

# fig = px.line(sacog_merged, x='Mon-Yr', y='Market Time', color='County', facet_col='County', template='plotly_white',
#                facet_col_wrap=2, title='Median Time on Market of Existing Detached Homes for SACOG Counties',
#                  labels={
#                      "Market Time": "Time (in days)"
#                  })

# fig.update_layout(yaxis_title = None)

# fig.show()