In [21]:
# Packages

# General
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
import re
from datetime import date
import math
import seaborn as sns

# Plotting
import matplotlib.pyplot as plt
import plotly
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio

In [22]:
# Define user
user = os.getlogin()
path_users = os.path.join('C:\\Users', user)

# Set file paths
if user == 'jfontes':
    # Git
    path_git = os.path.join(path_users, 'Documents', 'Projects', 'Regional-Monitoring', 'Indicator_Gen')
    
    # SharePoint
    path_sp   = os.path.join(path_users, 'Sacramento Area Council of Governments\Regional Monitoring and Reporting - Documents')
    path_agol = os.path.join(path_sp, 'Process Revamp', 'Task 8. Reproduce Progress Report indicators', 'Indicator Data', 'BLS Data')
    path_main = os.path.join(path_sp, 'Data')
    
if user in ['jchoy', 'aazawii']:
    # Git
    path_git = os.path.join(path_users, 'Documents', 'Python Projects', 'Regional-Monitoring', 'Indicator_Gen')
    path_sp   = os.path.join(path_users, 'Sacramento Area Council of Governments\Regional Monitoring and Reporting - Documents')
    path_agol = os.path.join(path_sp, 'Process Revamp', 'Task 8. Reproduce Progress Report indicators', 'Indicator Data', 'BLS Data')
    path_main = os.path.join(path_sp, 'Data')
    
path_config0 = os.path.join(path_git, 'config')
path_config  = os.path.join(path_git, 'Python Code', 'BLS', 'config')



print(user)
print(path_git)

jchoy
C:\Users\jchoy\Documents\Python Projects\Regional-Monitoring\Indicator_Gen

<>:11: SyntaxWarning:

invalid escape sequence '\R'

<>:18: SyntaxWarning:

invalid escape sequence '\R'

<>:11: SyntaxWarning:

invalid escape sequence '\R'

<>:18: SyntaxWarning:

invalid escape sequence '\R'

C:\Users\jchoy\AppData\Local\Temp\ipykernel_19332\1373476644.py:11: SyntaxWarning:

invalid escape sequence '\R'

C:\Users\jchoy\AppData\Local\Temp\ipykernel_19332\1373476644.py:18: SyntaxWarning:

invalid escape sequence '\R'

In [23]:
## User defined functions
exec(open(os.path.join(path_config0, 'Functions.py')).read())

In [24]:
# Set indicator
indicator_name = 'Jobs_1'

# Impoting data
# df_jobs = pd.read_csv(os.path.join(path_agol, indicator_name, indicator_name + '_MSA_BLS_SMU.csv'))
df_msa = pd.read_excel(os.path.join(path_main, 'Vibrant and Inclusive Places', 'Economy', 'Jobs', 'Jobs_1 Total', indicator_name + ' MSA BLS SMU.xlsx'     ), sheet_name = 'MSA'     )
df_nat = pd.read_excel(os.path.join(path_main, 'Vibrant and Inclusive Places', 'Economy', 'Jobs', 'Jobs_1 Total', indicator_name + ' National BLS CEU.xlsx'), sheet_name = 'National')

df_jobs = pd.concat([df_msa, df_nat])
df_jobs

,date_,Geography,Variable,Value,Percentage
0,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",All,1357800.0,NaN
1,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,201300.0,14.825453
2,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",Total Private,1156500.0,85.174547
3,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",All,1352800.0,NaN
4,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,200500.0,14.821112
...,...,...,...,...,...
874,2000-02-01,National,Government,20881000.0,16.105048
875,2000-02-01,National,Total Private,108774000.0,83.894952
876,2000-01-01,National,All,128993000.0,NaN
877,2000-01-01,National,Government,20491000.0,15.885358
878,2000-01-01,National,Total Private,108502000.0,84.114642

In [6]:
# JARED CHANGES 

# Perhaps a problem in how Josh's listed code is to xlsx and i only have access to csv

path = "C:\\Users\\jchoy\\Documents\\Jobs_1_MSA_BLS_SMU.csv"

df_msa = pd.read_csv(path)

path_2 = "C:\\Users\\jchoy\\Documents\\Jobs_1_National_BLS_CEU.csv"

df_nat = pd.read_csv(path_2)

df_jobs = pd.concat([df_msa, df_nat])

# Display the first few rows of the DataFrame
display(df_jobs.head())

,date_,Geography,Variable,Value,Percentage
0,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,201300.0,14.825453
1,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",Total Private,1156500.0,85.174547
2,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,200500.0,14.821112
3,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",Total Private,1152300.0,85.178888
4,2024-03-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,200000.0,14.841199

In [7]:
df_jobs

,date_,Geography,Variable,Value,Percentage
0,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,201300.0,14.825453
1,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",Total Private,1156500.0,85.174547
2,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,200500.0,14.821112
3,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",Total Private,1152300.0,85.178888
4,2024-03-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,200000.0,14.841199
...,...,...,...,...,...
581,2000-03-01,National,Total Private,109632000.0,83.847283
582,2000-02-01,National,Government,20881000.0,16.105048
583,2000-02-01,National,Total Private,108774000.0,83.894952
584,2000-01-01,National,Government,20491000.0,15.885358
585,2000-01-01,National,Total Private,108502000.0,84.114642

In [8]:
df_plot = df_jobs.copy()

In [9]:
df_plot = df_plot[df_plot['Variable'] == 'All'].reset_index(drop = True)
df_plot

Empty DataFrame
Columns: [date_, Geography, Variable, Value, Percentage]
Index: []

## Month to Month

In [25]:
df_plot = df_jobs.copy()
#edit
display(df_plot.head())

df_plot = df_plot[df_plot['Variable'] == 'All'].reset_index(drop = True)
df_plot = df_plot.drop(['Variable', 'Percentage'], axis = 1)
#edit
display(df_plot.head())


df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, True])
df_plot['Jobs_GR'] = df_plot['Value'].pct_change()*100
df_plot.loc[df_plot['date_'] == '2000-01-01', 'Jobs_GR'] = np.nan
df_plot.loc[df_plot['Jobs_GR'] == np.inf, 'Jobs_GR'] = np.nan
df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, False])
# edit
display(df_plot.head())

# SACOG roll up
conditions = [   
       df_plot['Geography'].str.contains('Sac|Yuba')
    , ~df_plot['Geography'].str.contains('Sac|Yuba|National')
    ,  df_plot['Geography'].str.contains('National')
             ]
choices = ['SACOG', 'Peer MSA', 'National']
df_plot['Groups'] = np.select(conditions, choices)
wm = lambda x: np.average(x, weights = df_plot.loc[x.index, "Value"]) # weighted average
df_plot = df_plot.groupby(['date_', 'Groups'], as_index = False).agg(Value = ('Value', 'sum'), Jobs_GR = ('Jobs_GR', wm))
df_plot = df_plot.sort_values(['Groups', 'date_'], ascending = [True, False])

df_plot = df_plot.rename(columns = {'Jobs_GR':'Growth Rate'})


df_plot

,date_,Geography,Variable,Value,Percentage
0,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",All,1357800.0,NaN
1,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,201300.0,14.825453
2,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",Total Private,1156500.0,85.174547
3,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",All,1352800.0,NaN
4,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",Government,200500.0,14.821112

        date_                                    Geography      Value
0  2024-05-01  Austin-Round Rock-Georgetown, TX Metro Area  1357800.0
1  2024-04-01  Austin-Round Rock-Georgetown, TX Metro Area  1352800.0
2  2024-03-01  Austin-Round Rock-Georgetown, TX Metro Area  1347600.0
3  2024-02-01  Austin-Round Rock-Georgetown, TX Metro Area  1349000.0
4  2024-01-01  Austin-Round Rock-Georgetown, TX Metro Area  1333900.0

,date_,Geography,Value,Jobs_GR
0,2024-05-01,"Austin-Round Rock-Georgetown, TX Metro Area",1357800.0,0.369604
1,2024-04-01,"Austin-Round Rock-Georgetown, TX Metro Area",1352800.0,0.385871
2,2024-03-01,"Austin-Round Rock-Georgetown, TX Metro Area",1347600.0,-0.103781
3,2024-02-01,"Austin-Round Rock-Georgetown, TX Metro Area",1349000.0,1.132019
4,2024-01-01,"Austin-Round Rock-Georgetown, TX Metro Area",1333900.0,-1.680548

          date_    Groups        Value  Growth Rate
876  2024-05-01  National  158918000.0     0.580376
873  2024-04-01  National  158001000.0     0.503149
870  2024-03-01  National  157210000.0     0.420949
867  2024-02-01  National  156551000.0     0.719929
864  2024-01-01  National  155432000.0    -1.792518
..          ...       ...          ...          ...
14   2000-05-01     SACOG     840800.0     0.852149
11   2000-04-01     SACOG     833700.0     0.433891
8    2000-03-01     SACOG     830100.0     0.986509
5    2000-02-01     SACOG     822000.0     0.612618
2    2000-01-01     SACOG     817000.0          NaN

[879 rows x 4 columns]

In [26]:
fig = px.line(df_plot, x = 'date_', y = 'Growth Rate', color = 'Groups', template = 'plotly_white')

fig.update_yaxes(tick0=0, dtick=1)
fig.update_layout(legend_title=None, title='Monthly Job Growth Comparison: Sacramento and other Mid-Sized Metro Areas')

fig.show()

## January to January

In [27]:
df_plot = df_jobs.copy()

df_plot = df_plot[df_plot['Variable'] == 'All']
df_plot = df_plot.drop(['Variable', 'Percentage'], axis = 1)


df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, True])
df_plot = df_plot[df_plot['date_'].str.contains('01-01')].reset_index(drop = True)
df_plot['Jobs_GR'] = df_plot['Value'].pct_change()*100
df_plot.loc[df_plot['date_'] == '2000-01-01', 'Jobs_GR'] = np.nan
df_plot.loc[df_plot['Jobs_GR'] == np.inf, 'Jobs_GR'] = np.nan
df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, False])

wm = lambda x: np.average(x, weights = df_plot.loc[x.index, "Value"]) # weighted average

# SACOG roll up
conditions = [   
       df_plot['Geography'].str.contains('Sac|Yuba')
    , ~df_plot['Geography'].str.contains('Sac|Yuba|National')
    ,  df_plot['Geography'].str.contains('National')
             ]
choices = ['SACOG', 'Peer MSA', 'National']
df_plot['Groups'] = np.select(conditions, choices)
df_plot = df_plot.groupby(['date_', 'Groups'], as_index = False).agg(Value = ('Value', 'sum'), Jobs_GR = ('Jobs_GR', wm))
df_plot = df_plot.sort_values(['Groups', 'date_'], ascending = [True, False])


# Set up groups
conditions = [   
         df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2000, 2007, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2008, 2011, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2012, 2020, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2021, 2021, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2022, 2024, 1)))
             ]
# choices = ["Pre Recession", "Recession", "Post Recession", "Covid", "Post Covid"]
choices = ["Pre Recession (2000-2008)", "Recession (2008-2011)", "Post Recession (2011-2020)", "Covid (2020)", "Post Covid (2020-2024)"]
# Jared to fix year labels for plot below

df_plot["Period"] = np.select(conditions, choices)

df_plot = df_plot.dropna()

wm = lambda x: np.average(x, weights = df_plot.loc[x.index, "Value"])
df_plot1 = df_plot.groupby(['Groups', 'Period'], as_index = False)['Jobs_GR'].agg(np.mean)
df_plot2 = df_plot.groupby(['Groups'          ], as_index = False)['Jobs_GR'].agg(np.mean)
df_plot2['Period'] = 'Total'
df_plot = pd.concat([df_plot1, df_plot2])

period_order = ["Total", "Pre Recession (2000-2008)", "Recession (2008-2011)", "Post Recession (2011-2020)", "Covid (2020)", "Post Covid (2020-2024)"]

df_plot['Period_Sort'] = pd.Categorical(df_plot['Period'], period_order)
df_plot = df_plot.sort_values(by=['Groups', 'Period_Sort'], ascending=[True, True])
df_plot = df_plot.drop(['Period_Sort'], axis=1)

# df_plot['Period_Sort'] = pd.Categorical(df_plot['Period'], ["Total", "Pre Recession", "Recession", "Post Recession", "Covid", "Post Covid"])
# df_plot = df_plot.sort_values(by = ['Groups', 'Period_Sort'], ascending = [True, True])
# df_plot = df_plot.drop(['Period_Sort'], axis = 1)

df_plot = df_plot.rename(columns = {'Jobs_GR':'Growth Rate', 'Period':'Time Period'})

df_plot

C:\Users\jchoy\AppData\Local\Temp\ipykernel_19332\4160776990.py:45: FutureWarning:

The provided callable <function mean at 0x00000252BC8E89A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

C:\Users\jchoy\AppData\Local\Temp\ipykernel_19332\4160776990.py:46: FutureWarning:

The provided callable <function mean at 0x00000252BC8E89A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

      Groups                 Time Period  Growth Rate
0   National                       Total     0.805051
3   National   Pre Recession (2000-2008)     0.692447
4   National       Recession (2008-2011)    -1.215118
2   National  Post Recession (2011-2020)     1.715466
0   National                Covid (2020)    -6.052407
1   National      Post Covid (2020-2024)     3.315927
1   Peer MSA                       Total     1.147594
8   Peer MSA   Pre Recession (2000-2008)     0.930689
9   Peer MSA       Recession (2008-2011)    -1.408957
7   Peer MSA  Post Recession (2011-2020)     2.422523
5   Peer MSA                Covid (2020)    -5.765145
6   Peer MSA      Post Covid (2020-2024)     3.541897
2      SACOG                       Total     1.410370
13     SACOG   Pre Recession (2000-2008)     2.227283
14     SACOG       Recession (2008-2011)    -2.575737
12     SACOG  Post Recession (2011-2020)     2.521798
10     SACOG                Covid (2020)    -5.573432
11     SACOG      Post Covid (2020-2024)     3.812702

In [28]:
## Jared to fix the labels on the plot add years

fig = px.bar(df_plot, x='Time Period', y='Growth Rate', color='Groups', barmode='group', template='plotly_white')
fig.update_yaxes(tick0=0, dtick=1)
fig.update_xaxes(tickangle=0)  
fig.update_layout(legend_title=None, title='Annual Job Growth Comparison: Sacramento and other Mid-Sized Metro Areas (January)')
fig.update_layout(xaxis = dict(tickfont = dict(size=10)))
fig.show()

## September to September

In [29]:
df_plot = df_jobs.copy()

df_plot = df_plot[df_plot['Variable'] == 'All']
df_plot = df_plot.drop(['Variable', 'Percentage'], axis = 1)


df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, True])
df_plot = df_plot[df_plot['date_'].str.contains('09-01')].reset_index(drop = True)
df_plot['Jobs_GR'] = df_plot['Value'].pct_change()*100
df_plot.loc[df_plot['date_'] == '2000-09-01', 'Jobs_GR'] = np.nan
df_plot.loc[df_plot['Jobs_GR'] == np.inf, 'Jobs_GR'] = np.nan
df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, False])

wm = lambda x: np.average(x, weights = df_plot.loc[x.index, "Value"]) # weighted average

# SACOG roll up
conditions = [   
       df_plot['Geography'].str.contains('Sac|Yuba')
    , ~df_plot['Geography'].str.contains('Sac|Yuba|National')
    ,  df_plot['Geography'].str.contains('National')
             ]
choices = ['SACOG', 'Peer MSA', 'National']
df_plot['Groups'] = np.select(conditions, choices)
df_plot = df_plot.groupby(['date_', 'Groups'], as_index = False).agg(Value = ('Value', 'sum'), Jobs_GR = ('Jobs_GR', wm))
df_plot = df_plot.sort_values(['Groups', 'date_'], ascending = [True, False])


# Set up groups
conditions = [   
         df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2000, 2007, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2008, 2011, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2012, 2019, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2020, 2020, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2021, 2024, 1)))
             ]
# choices = ["Pre Recession", "Recession", "Post Recession", "Covid", "Post Covid"]
choices = ["Pre Recession (2000-2008)", "Recession (2008-2011)", "Post Recession (2011-2020)", "Covid (2020)", "Post Covid (2020-2024)"]

df_plot["Period"] = np.select(conditions, choices)

df_plot = df_plot.dropna()

wm = lambda x: np.average(x, weights = df_plot.loc[x.index, "Value"])
df_plot1 = df_plot.groupby(['Groups', 'Period'], as_index = False)['Jobs_GR'].agg(np.mean)
df_plot2 = df_plot.groupby(['Groups'          ], as_index = False)['Jobs_GR'].agg(np.mean)
df_plot2['Period'] = 'Total'
df_plot = pd.concat([df_plot1, df_plot2])

period_order = ["Total", "Pre Recession (2000-2008)", "Recession (2008-2011)", "Post Recession (2011-2020)", "Covid (2020)", "Post Covid (2020-2024)"]

df_plot['Period_Sort'] = pd.Categorical(df_plot['Period'], period_order)
df_plot = df_plot.sort_values(by=['Groups', 'Period_Sort'], ascending=[True, True])
df_plot = df_plot.drop(['Period_Sort'], axis=1)

# df_plot['Period_Sort'] = pd.Categorical(df_plot['Period'], ["Total", "Pre Recession", "Recession", "Post Recession", "Covid", "Post Covid"])
# df_plot = df_plot.sort_values(by = ['Groups', 'Period_Sort'], ascending = [True, True])
# df_plot = df_plot.drop(['Period_Sort'], axis = 1)

df_plot = df_plot.rename(columns = {'Jobs_GR':'Growth Rate', 'Period':'Time Period'})

df_plot

C:\Users\jchoy\AppData\Local\Temp\ipykernel_19332\219321491.py:44: FutureWarning:

The provided callable <function mean at 0x00000252BC8E89A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

C:\Users\jchoy\AppData\Local\Temp\ipykernel_19332\219321491.py:45: FutureWarning:

The provided callable <function mean at 0x00000252BC8E89A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

      Groups                 Time Period  Growth Rate
0   National                       Total     0.724172
3   National   Pre Recession (2000-2008)     0.614162
4   National       Recession (2008-2011)    -0.840120
2   National  Post Recession (2011-2020)     1.679018
0   National                Covid (2020)    -6.305194
1   National      Post Covid (2020-2024)     3.384880
1   Peer MSA                       Total     1.035696
8   Peer MSA   Pre Recession (2000-2008)     0.757988
9   Peer MSA       Recession (2008-2011)    -0.988706
7   Peer MSA  Post Recession (2011-2020)     2.381716
5   Peer MSA                Covid (2020)    -6.573446
6   Peer MSA      Post Covid (2020-2024)     4.004681
2      SACOG                       Total     1.214301
13     SACOG   Pre Recession (2000-2008)     1.853275
14     SACOG       Recession (2008-2011)    -2.078196
12     SACOG  Post Recession (2011-2020)     2.630944
10     SACOG                Covid (2020)    -5.932389
11     SACOG      Post Covid (2020-2024)     3.815368

In [30]:
# px.bar(df_plot, x = 'Period', y = 'Jobs_GR', facet_col = 'Groups')
fig = px.bar(df_plot, x = 'Time Period', y = 'Growth Rate', color = 'Groups', barmode = 'group', template = 'plotly_white')

fig.update_yaxes(tick0=0, dtick=1)
fig.update_xaxes(tickangle=0)  
fig.update_layout(legend_title=None, title='Annual Job Growth Comparison: Sacramento and other Mid-Sized Metro Areas (September)')
fig.update_layout(xaxis = dict(tickfont = dict(size=10)))
fig.show()

# Note, might need to change this plot's eras. COVID years in September might be considered diff from January.

## By Presidential Administration

In [31]:
df_plot = df_jobs.copy()

df_plot = df_plot[df_plot['Variable'] == 'All']
df_plot = df_plot.drop(['Variable', 'Percentage'], axis = 1)


df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, True])
df_plot = df_plot[df_plot['date_'].str.contains('01-01')].reset_index(drop = True)
df_plot['Jobs_GR'] = df_plot['Value'].pct_change()*100
df_plot.loc[df_plot['date_'] == '2000-01-01', 'Jobs_GR'] = np.nan
df_plot.loc[df_plot['Jobs_GR'] == np.inf, 'Jobs_GR'] = np.nan
df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, False])

wm = lambda x: np.average(x, weights = df_plot.loc[x.index, "Value"]) # weighted average

# SACOG roll up
conditions = [   
       df_plot['Geography'].str.contains('Sac|Yuba')
    , ~df_plot['Geography'].str.contains('Sac|Yuba|National')
    ,  df_plot['Geography'].str.contains('National')
             ]
choices = ['SACOG', 'Peer MSA', 'National']
df_plot['Groups'] = np.select(conditions, choices)
df_plot = df_plot.groupby(['date_', 'Groups'], as_index = False).agg(Value = ('Value', 'sum'), Jobs_GR = ('Jobs_GR', wm))
df_plot = df_plot.sort_values(['Groups', 'date_'], ascending = [True, False])


# Set up groups
conditions = [   
         df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2001, 2009, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2010, 2017, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2018, 2021, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2022, 2024, 1)))
             ]
choices = ["Bush", "Obama", "Trump", "Biden"]
df_plot["Administration"] = np.select(conditions, choices)

df_plot = df_plot.dropna()

wm = lambda x: np.average(x, weights = df_plot.loc[x.index, "Value"])
df_plot1 = df_plot.groupby(['Groups', 'Administration'], as_index = False)['Jobs_GR'].agg(np.mean)
df_plot2 = df_plot.groupby(['Groups'          ], as_index = False)['Jobs_GR'].agg(np.mean)
df_plot2['Administration'] = 'Total'
df_plot = pd.concat([df_plot1, df_plot2])

df_plot['Period_Sort'] = pd.Categorical(df_plot['Administration'], ["Total", "Bush", "Obama", "Trump", "Biden"])
df_plot = df_plot.sort_values(by = ['Groups', 'Period_Sort'], ascending = [True, True])
df_plot = df_plot.drop(['Period_Sort'], axis = 1)

df_plot = df_plot.rename(columns = {'Jobs_GR':'Growth Rate'})

df_plot

C:\Users\jchoy\AppData\Local\Temp\ipykernel_19332\1595521532.py:41: FutureWarning:

The provided callable <function mean at 0x00000252BC8E89A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

C:\Users\jchoy\AppData\Local\Temp\ipykernel_19332\1595521532.py:42: FutureWarning:

The provided callable <function mean at 0x00000252BC8E89A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

      Groups Administration  Growth Rate
0   National          Total     0.805051
1   National           Bush     0.270313
2   National          Obama     1.050535
3   National          Trump    -0.365914
0   National          Biden     3.315927
1   Peer MSA          Total     1.147594
5   Peer MSA           Bush     0.352336
6   Peer MSA          Obama     1.673923
7   Peer MSA          Trump     0.088539
4   Peer MSA          Biden     3.541897
2      SACOG          Total     1.410370
9      SACOG           Bush     1.245824
10     SACOG          Obama     1.103777
11     SACOG          Trump     0.592039
8      SACOG          Biden     3.812702

In [32]:
fig = px.bar(df_plot, x = 'Administration', y = 'Growth Rate', color = 'Groups', barmode = 'group', template = 'plotly_white')

fig.update_yaxes(tick0=0, dtick=1)
fig.update_layout(legend_title=None, title='Annual Job Growth Comparison: Sacramento and other Mid-Sized Metro Areas (by Presidential Administration)')

fig.show()

In [33]:
df_plot = df_jobs.copy()

df_plot = df_plot[df_plot['Variable'] == 'All']
df_plot = df_plot.drop(['Variable', 'Percentage'], axis = 1)


df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, True])
df_plot = df_plot[df_plot['date_'].str.contains('01-01')].reset_index(drop = True)
df_plot['Jobs_GR'] = df_plot['Value'].pct_change()*100
df_plot.loc[df_plot['date_'] == '2000-01-01', 'Jobs_GR'] = np.nan
df_plot.loc[df_plot['Jobs_GR'] == np.inf, 'Jobs_GR'] = np.nan
df_plot = df_plot.sort_values(['Geography', 'date_'], ascending = [True, False])


# SACOG roll up
conditions = [   
       df_plot['Geography'].str.contains('Sac|Yuba')
    , ~df_plot['Geography'].str.contains('Sac|Yuba|National')
    ,  df_plot['Geography'].str.contains('National')
             ]
choices = ['SACOG', 'Peer MSA', 'National']
df_plot['Groups'] = np.select(conditions, choices)
df_plot = df_plot.groupby(['date_', 'Groups'], as_index = False).agg(Value = ('Value', 'sum'), Jobs_GR = ('Jobs_GR', wm))
df_plot = df_plot.sort_values(['Groups', 'date_'], ascending = [True, False])


# Set up groups
conditions = [   
         df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2001, 2009, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2010, 2017, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2018, 2021, 1)))
       , df_plot['date_'].str.contains("|".join(str(year) for year in sequence(2022, 2024, 1)))
             ]
choices = ["Bush", "Obama", "Trump", "Biden"]
df_plot["Administration"] = np.select(conditions, choices)

df_plot = df_plot.dropna()

df_plot = df_plot.sort_values(by = ['Groups', 'date_'], ascending = [True, True])

df_plot = df_plot.rename(columns = {'Jobs_GR':'Growth Rate'})

df_plot

         date_    Groups        Value  Growth Rate Administration
3   2001-01-01  National  130667000.0     1.297745           Bush
6   2002-01-01  National  128876000.0    -1.370660           Bush
9   2003-01-01  National  128561000.0    -0.244421           Bush
12  2004-01-01  National  128709000.0     0.115120           Bush
15  2005-01-01  National  130695000.0     1.543016           Bush
..         ...       ...          ...          ...            ...
62  2020-01-01     SACOG    1072900.0     2.314496          Trump
65  2021-01-01     SACOG    1013100.0    -5.573432          Trump
68  2022-01-01     SACOG    1077200.0     6.327253          Biden
71  2023-01-01     SACOG    1100300.0     2.145007          Biden
74  2024-01-01     SACOG    1132900.0     2.965845          Biden

[72 rows x 5 columns]

In [35]:
fig = px.line(df_plot, x = 'date_', y = 'Growth Rate', color = 'Groups', template = 'plotly_white')

fig.update_yaxes(tick0=0, dtick=1)
fig.update_layout(legend_title=None, title='Monthly Job Growth Comparison: Sacramento and other Mid-Sized Metro Areas', xaxis_title="Date",)
fig.add_vline(x = '2008-01-01', line_dash = 'dash')
fig.add_vline(x = '2017-01-01', line_dash = 'dash')
fig.add_vline(x = '2021-01-01', line_dash = 'dash')
fig.add_hline(y = 0, line_dash = 'dash', line_color = 'gray')


fig.show()