In [107]:


export = True


import pandas as pd
from pathlib import Path
import os
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
pd.options.display.float_format = '{:.2f}'.format


PATH_GIT     = Path.home() / 'Documents' / 'Projects' / 'Regional-Monitoring' / 'Indicator_Gen'
PATH_CONFIG0 = PATH_GIT / 'config'

PATH_PLOTS = Path(r"\\webmapping-svr\c$\inetpub\wwwroot\monitoring")
print('Export Location: ' + str(PATH_PLOTS))

import sys
sys.path.append(str(PATH_CONFIG0))
import plot as pt

Export Location: \\webmapping-svr\c$\inetpub\wwwroot\monitoring

***

Safety_1

***

In [108]:

indicator = 'Safety_1'
plot_name = 'toggle_fatality_rate'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot1 = df_mpo  .copy()
df_plot2 = df_state.copy()


df_plot1 = df_plot1.rename(columns = {'MPO'  :'Geography'})
df_plot1['Geography'] = 'Sacramento Region'
df_plot2 = df_plot2.rename(columns = {'State':'Geography'})
df_plot2['Geography'] = 'California'

df_plot = pd.concat([df_plot1, df_plot2])
df_plot = df_plot.sort_values(['Geography', 'Year'], ascending = [False, True])
df_plot = df_plot.reset_index(drop = True)

display(df_plot.head(), df_plot.tail())


color_map  = {
    'Sacramento Region': '#9DC209'
    , 'California': '#1E90FF'
}

fig=go.Figure()

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Fatalities 100 mvmt_5 Year Rolling Average'])

    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Fatalities 100 mvmt_5 Year Rolling Average'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}'
    ))

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Fatalities 100 mvmt'])
    
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Fatalities 100 mvmt'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}',
        visible=False
    ))

# Create buttons for toggling
buttons = [
    dict(
        label='5 Year Average',
        method='update',
        args=[
            {'visible': [True, True,False, False]},
            {'xaxis': {'tickangle': 0}}
        ]
    ),
    dict(
        label='Annual',
        method='update',
        args=[
            {'visible': [False, False, True, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.1,
            yanchor="top"
        )
    ]
)

title = 'Traffic Fatality Rates'
fig.update_yaxes(tick0=0, dtick=0.2, range = [0.5, 2.1])
fig.update_traces(hovertemplate='%{y}')
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.55))

pt.plot_agol(fig, export, title, indicator, plot_name)

,Geography,Year,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
0,Sacramento Region,2014,0.85,NaN,3.61,NaN
1,Sacramento Region,2015,1.06,NaN,3.76,NaN
2,Sacramento Region,2016,1.23,NaN,3.92,NaN
3,Sacramento Region,2017,1.21,NaN,4.26,NaN
4,Sacramento Region,2018,1.21,1.11,5.23,4.15

,Geography,Year,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
17,California,2020,1.33,1.15,5.15,4.50
18,California,2021,1.44,1.21,5.82,4.89
19,California,2022,1.44,1.27,5.68,5.20
20,California,2023,1.30,1.32,5.27,5.32
21,California,2024,NaN,NaN,NaN,NaN

In [109]:

indicator = 'Safety_1'
plot_name = 'toggle_injury_rate'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')



df_plot1 = df_mpo  .copy()
df_plot2 = df_state.copy()


df_plot1 = df_plot1.rename(columns = {'MPO'  :'Geography'})
df_plot1['Geography'] = 'Sacramento Region'
df_plot2 = df_plot2.rename(columns = {'State':'Geography'})
df_plot2['Geography'] = 'California'

df_plot = pd.concat([df_plot1, df_plot2])
df_plot = df_plot.sort_values(['Geography', 'Year'], ascending = [False, True])
df_plot = df_plot.reset_index(drop = True)
print(df_plot.columns.tolist())

display(df_plot.head(), df_plot.tail())


color_map  = {
    'Sacramento Region': '#9DC209'
    , 'California': '#1E90FF'
}

fig=go.Figure()

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Serious injuries 100 mvm_5 Year Rolling Average'])

    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Serious injuries 100 mvm_5 Year Rolling Average'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}'
    ))

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Serious injuries 100 mvm'])
    
    fig.add_trace(go.Bar(
        x=df_cat['Year'].astype(str),
        y=df_cat['Serious injuries 100 mvm'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}',
        visible=False
    ))

# Create buttons for toggling
buttons = [
    dict(
        label='5 Year Average',
        method='update',
        args=[
            {'visible': [True, True,False, False]},
            {'xaxis': {'tickangle': 0}}
        ]
    ),
    dict(
        label='Annual',
        method='update',
        args=[
            {'visible': [False, False, True, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.1,
            yanchor="top"
        )
    ]
)


title = 'Traffic Serious Injury Rates'
fig.update_yaxes(tick0=0, dtick=1, range = [0, 8.5])
fig.update_traces(hovertemplate='%{y}')

fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.55))
pt.plot_agol(fig, export, title, indicator, plot_name)

['Geography', 'Year', 'Fatalities 100 mvmt', 'Fatalities 100 mvmt_5 Year Rolling Average', 'Serious injuries 100 mvm', 'Serious injuries 100 mvm_5 Year Rolling Average']

,Geography,Year,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
0,Sacramento Region,2014,0.85,NaN,3.61,NaN
1,Sacramento Region,2015,1.06,NaN,3.76,NaN
2,Sacramento Region,2016,1.23,NaN,3.92,NaN
3,Sacramento Region,2017,1.21,NaN,4.26,NaN
4,Sacramento Region,2018,1.21,1.11,5.23,4.15

,Geography,Year,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
17,California,2020,1.33,1.15,5.15,4.50
18,California,2021,1.44,1.21,5.82,4.89
19,California,2022,1.44,1.27,5.68,5.20
20,California,2023,1.30,1.32,5.27,5.32
21,California,2024,NaN,NaN,NaN,NaN

***

Safety_2

***

In [110]:
import plot as pt
indicator = 'Safety_2'
plot_name = 'toggle_nonmotorized_fatalities'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot = df_mpo.copy()
df_plot = df_plot.dropna()

display(df_plot.head())

# Create figure with both traces
fig = go.Figure()

# Add yearly trace
fig.add_trace(go.Bar(
    x=df_plot['Year'],
    y=df_plot['Non motorized fatalities_5 Year Rolling Average'],
    marker_color='#1E90FF',
    name='5 Year Average',
    visible=True,
    hovertemplate='%{y}<extra></extra>'
))

# Add monthly trace
fig.add_trace(go.Bar(
    x=df_plot['Year'],
    y=df_plot['Non motorized fatalities'],
    marker_color='#1E90FF',
    name='Annual',
    visible=False,
    hovertemplate='%{y}<extra></extra>'
))

# Create buttons for toggling
buttons = [
    dict(
        label='5 Year Average',
        method='update',
        args=[
            {'visible': [True, False]},
            {'xaxis': {'tickangle': 0}}
        ]
    ),
    dict(
        label='Annual',
        method='update',
        args=[
            {'visible': [False, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.1,
            yanchor="top"
        )
    ]
)

#fig = px.bar(df_plot, y='Non motorized fatalities_5 Year Rolling Average', x='Year')
fig.update_traces(marker_color='#1E90FF')

# title = '<b>Non-Motorized Fatalities, 5 Year Rolling Average</b> <br> <sup>Sacramento Region</sup>'
title = 'Non-Motorized Fatalities'
fig.update_yaxes(tick0=0, dtick=10, range = [0, 105])
fig.update_traces(hovertemplate='%{y}')


pt.plot_agol(fig, export, title, indicator, plot_name)

,MPO,Year,Non motorized fatalities,Non motorized fatalities_5 Year Rolling Average,Non motorized serious in,Non motorized serious in_5 Year Rolling Average
4,SACOG,2018,78,70.60,222,204.00
5,SACOG,2019,82,76.80,231,211.40
6,SACOG,2020,73,78.20,210,214.80
7,SACOG,2021,98,81.40,255,228.00
8,SACOG,2022,126,91.40,234,230.40

In [103]:
import plot as pt
indicator = 'Safety_2'
plot_name = 'toggle_nonmotorized_injuries'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot = df_mpo.copy()

df_plot = df_plot.dropna()

display(df_plot.head())

# Create figure with both traces
fig = go.Figure()

# Add yearly trace
fig.add_trace(go.Bar(
    x=df_plot['Year'],
    y=df_plot['Non motorized serious in_5 Year Rolling Average'],
    marker_color='#1E90FF',
    name='5 Year Average',
    visible=True,
    hovertemplate='%{y}<extra></extra>'
))

# Add monthly trace
fig.add_trace(go.Bar(
    x=df_plot['Year'],
    y=df_plot['Non motorized serious in'],
    marker_color='#1E90FF',
    name='Annual',
    visible=False,
    hovertemplate='%{y}<extra></extra>'
))

# Create buttons for toggling
buttons = [
    dict(
        label='5 Year Average',
        method='update',
        args=[
            {'visible': [True, False]},
            {'xaxis': {'tickangle': 0}}
        ]
    ),
    dict(
        label='Annual',
        method='update',
        args=[
            {'visible': [False, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.1,
            yanchor="top"
        )
    ]
)

#fig = px.bar(df_plot, y='Non motorized serious in_5 Year Rolling Average', x='Year')
fig.update_traces(marker_color='#1E90FF')

# title = '<b>Non-Motorized Serious Injuries, 5 Year Rolling Average</b> <br> <sup>Sacramento Region</sup>'
title = 'Non-Motorized Serious Injuries'
fig.update_yaxes(tick0=0, dtick=50, range = [0, 275])
fig.update_traces(hovertemplate='%{y}')


pt.plot_agol(fig, export, title, indicator, plot_name)

,MPO,Year,Non motorized fatalities,Non motorized fatalities_5 Year Rolling Average,Non motorized serious in,Non motorized serious in_5 Year Rolling Average
4,SACOG,2018,78,70.60,222,204.00
5,SACOG,2019,82,76.80,231,211.40
6,SACOG,2020,73,78.20,210,214.80
7,SACOG,2021,98,81.40,255,228.00
8,SACOG,2022,126,91.40,234,230.40

***

Safety_3

***

In [94]:
export = False
indicator_name = 'Safety_3'
plot_name = 'ej'


df_mpo = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator_name} TIMS.xlsx", sheet_name='Region', skiprows=1)
df_mpo = df_mpo[['Year', 'Fatal', 'Serious Injury', 'Total Injury']]


df_plot = df_mpo.copy()

df_plot.columns = ['Year', 'Fatal Collisions', 'Serious Injury Collisions', 'Total Injury Collisions']
df_plot = pd.melt(df_plot, id_vars = ['Year'], var_name = 'Metric', value_name = 'Percentage')
df_plot['Percentage'] = round(df_plot['Percentage']*100, 1)

display(df_plot.head())


color_map = {
    'Fatal Collisions': '#1F45FC'
    , 'Serious Injury Collisions': '#1E90FF'
    , 'Total Injury Collisions': '#9DC209'
}

fig = px.bar(df_plot, y='Percentage', x='Year'
             , color='Metric'
             , facet_col='Metric'
             , color_discrete_map=color_map)

title = '<b>Percent of Collisions Occurring in Environmental Justice Communities</b>  <br><sup>Non-freeway collisions in 6-county Sacramento region</sup><br><br>'
fig.update_yaxes(tick0=0, dtick=10, range = [0, 102], ticksuffix='%')
fig.update_traces(hovertemplate='%{y}')
fig.update_xaxes(dtick=2)
fig['layout']['xaxis2']['title']['text']=''
fig['layout']['xaxis3']['title']['text']=''
fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))

for annotation in fig['layout']['annotations']:
    annotation['y'] = -0.1
    
pt.plot_agol(fig, export, title, indicator, plot_name)

   Year            Metric  Percentage
0  2012  Fatal Collisions       41.60
1  2013  Fatal Collisions       50.30
2  2014  Fatal Collisions       51.50
3  2015  Fatal Collisions       49.00
4  2016  Fatal Collisions       53.30

***

Safety_4

***

In [101]:
export = True
import plot as pt
indicator = 'Safety_4'
plot_name = 'toggle_fatalities'


df_mpo = pd.read_excel(os.path.join(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"), sheet_name='MPO')



df_plot = df_mpo.copy()

df_plot = df_plot.dropna()
df_plot = df_plot.sort_values(['Year', 'Category'], ascending = [False, True])

display(df_plot.head())


color_map  = {
    'Bicyclists': '#9DC209'
    , 'Pedestrians': '#1E90FF'
}

fig=go.Figure()

for category, color in color_map.items():
    df_cat = df_plot[df_plot['Category'] == category]
    df_cat=df_cat.sort_values('Year',ascending=True)
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Fatalities_5 Year Average'],
        name=category,
        marker=dict(color=color),
        hovertemplate='%{y}'
    ))

for category, color in color_map.items():
    df_cat = df_plot[df_plot['Category'] == category]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat[df_cat['Fatalities']!=0]
    
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Fatalities'],
        name=category,
        marker=dict(color=color),
        hovertemplate='%{y}',
        visible=False
    ))

# Create buttons for toggling
buttons = [
    dict(
        label='5 Year Average',
        method='update',
        args=[
            {'visible': [True, True,False, False]},
            {'xaxis': {'tickangle': 0}}
        ]
    ),
    dict(
        label='Annual',
        method='update',
        args=[
            {'visible': [False, False, True, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.1,
            yanchor="top"
        )
    ]
)


title = 'Fatalities'
fig.update_yaxes(tick0=0, dtick=10, range = [0, 101])
fig.update_traces(hovertemplate='%{y}')
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.55))

pt.plot_agol(fig, export, title, indicator, plot_name)

,MPO,Year,Category,Fatalities,Serious Injuries,Fatalities_5 Year Average,Serious Injuries_5 Year Average
0,SACOG,2024,Bicyclists,21,0,14.80,72.20
1,SACOG,2024,Pedestrians,69,0,88.00,136.20
2,SACOG,2023,Bicyclists,23,120,12.00,89.80
3,SACOG,2023,Pedestrians,93,189,89.80,168.80
4,SACOG,2022,Bicyclists,18,85,11.00,82.80

In [102]:
export = True
import plot as pt
indicator = 'Safety_4'
plot_name = 'toggle_serious_injuries'


df_mpo = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx", sheet_name='MPO')


df_plot = df_mpo.copy()

df_plot = df_plot.dropna()
df_plot = df_plot.sort_values(['Year', 'Category'], ascending = [False, True])

display(df_plot.head())


color_map  = {
    'Bicyclists': '#9DC209'
    , 'Pedestrians': '#1E90FF'
}

fig=go.Figure()

for category, color in color_map.items():
    df_cat = df_plot[df_plot['Category'] == category]
    df_cat=df_cat.sort_values('Year',ascending=True)
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Serious Injuries_5 Year Average'],
        name=category,
        marker=dict(color=color),
        hovertemplate='%{y}'
    ))

for category, color in color_map.items():
    df_cat = df_plot[df_plot['Category'] == category]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat[df_cat['Serious Injuries']!=0]
    
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Serious Injuries'],
        name=category,
        marker=dict(color=color),
        hovertemplate='%{y}',
        visible=False
    ))

# Create buttons for toggling
buttons = [
    dict(
        label='5 Year Average',
        method='update',
        args=[
            {'visible': [True, True,False, False]},
            {'xaxis': {'tickangle': 0}}
        ]
    ),
    dict(
        label='Annual',
        method='update',
        args=[
            {'visible': [False, False, True, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.1,
            yanchor="top"
        )
    ]
)
title='Serious Injuries'
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.6))
fig.update_yaxes(tick0=0, dtick=20, range = [0, 200])

#fig.update_layout(
    #title='Serious Injuries, 5 Year Rolling Average',
    #barmode='group',
    #xaxis_title='Year',
    #yaxis_title='Serious Injuries',
    #legend_title_text=''
#)







pt.plot_agol(fig, export, title, indicator, plot_name)

,MPO,Year,Category,Fatalities,Serious Injuries,Fatalities_5 Year Average,Serious Injuries_5 Year Average
0,SACOG,2024,Bicyclists,21,0,14.80,72.20
1,SACOG,2024,Pedestrians,69,0,88.00,136.20
2,SACOG,2023,Bicyclists,23,120,12.00,89.80
3,SACOG,2023,Pedestrians,93,189,89.80,168.80
4,SACOG,2022,Bicyclists,18,85,11.00,82.80