In [25]:


export = True


import pandas as pd
from pathlib import Path
import os
import plotly.express as px
import plotly.graph_objects as go
pd.options.display.float_format = '{:.2f}'.format


PATH_GIT     = Path.home() / 'Documents' / 'Projects' / 'Regional-Monitoring' / 'Indicator_Gen'
PATH_CONFIG0 = PATH_GIT / 'config'

PATH_PLOTS = Path(r"\\webmapping-svr\c$\inetpub\wwwroot\monitoring")
print('Export Location: ' + str(PATH_PLOTS))

import sys
sys.path.append(str(PATH_CONFIG0))
import plot as pt

Export Location: \\webmapping-svr\c$\inetpub\wwwroot\monitoring

***

Safety_1

***

In [44]:
indicator = 'Safety_1'
plot_name = 'toggle_fatality_rate'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot1 = df_mpo  .copy()
df_plot2 = df_state.copy()


df_plot1 = df_plot1.rename(columns = {'MPO'  :'Geography'})
df_plot1['Geography'] = 'Sacramento Region'
df_plot2 = df_plot2.rename(columns = {'State':'Geography'})
df_plot2['Geography'] = 'California'

df_plot = pd.concat([df_plot1, df_plot2])
df_plot = df_plot.sort_values(['Geography', 'Year'], ascending = [False, True])
df_plot = df_plot.reset_index(drop = True)

display(df_plot.head(), df_plot.tail())


color_map  = {
    'Sacramento Region': '#9DC209'
    , 'California': '#1E90FF'
}

fig=go.Figure()

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Fatalities 100 mvmt_5 Year Rolling Average'])

    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Fatalities 100 mvmt_5 Year Rolling Average'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}'
    ))

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Fatalities_5 Year Rolling Average'])
    
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Fatalities_5 Year Rolling Average'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}',
        visible=False
    ))

# Create buttons for toggling
buttons = [
    dict(
        label='Rate Per 100 MVMT',
        method='update',
        args=[
            {'visible': [True, True,False, False]}
        ]
    ),
    dict(
        label='Total',
        method='update',
        args=[
            {'visible': [False, False, True, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.18,
            yanchor="top"
        )
    ]
)

title = 'Traffic Fatalities, 5 Year Rolling Average'

fig.update_traces(hovertemplate='%{y}')
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.62))

pt.plot_agol(fig, export, title, indicator, plot_name)

,Geography,Year,Fatalities,Fatalities_5 Year Rolling Average,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries,Serious injuries_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
0,Sacramento Region,2014,183,NaN,0.85,NaN,773,NaN,3.61,NaN
1,Sacramento Region,2015,229,NaN,1.06,NaN,814,NaN,3.76,NaN
2,Sacramento Region,2016,271,NaN,1.23,NaN,862,NaN,3.92,NaN
3,Sacramento Region,2017,268,NaN,1.21,NaN,944,NaN,4.26,NaN
4,Sacramento Region,2018,269,244.00,1.21,1.11,1160,910.60,5.23,4.15

,Geography,Year,Fatalities,Fatalities_5 Year Rolling Average,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries,Serious injuries_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
17,California,2020,3982,3856.20,1.33,1.15,15392,15090.40,5.15,4.50
18,California,2021,4477,3980.80,1.44,1.21,18084,16055.60,5.82,4.89
19,California,2022,4537,4107.40,1.44,1.27,17916,16798.60,5.68,5.20
20,California,2023,4142,4175.00,1.30,1.32,16760,16919.00,5.27,5.32
21,California,2024,3671,4161.80,NaN,NaN,16324,16895.20,NaN,NaN

In [45]:

indicator = 'Safety_1'
plot_name = 'toggle_fatality_rate_annual'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot1 = df_mpo  .copy()
df_plot2 = df_state.copy()


df_plot1 = df_plot1.rename(columns = {'MPO'  :'Geography'})
df_plot1['Geography'] = 'Sacramento Region'
df_plot2 = df_plot2.rename(columns = {'State':'Geography'})
df_plot2['Geography'] = 'California'

df_plot = pd.concat([df_plot1, df_plot2])
df_plot = df_plot.sort_values(['Geography', 'Year'], ascending = [False, True])
df_plot = df_plot.reset_index(drop = True)

display(df_plot.head(), df_plot.tail())


color_map  = {
    'Sacramento Region': '#9DC209'
    , 'California': '#1E90FF'
}

fig=go.Figure()

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Fatalities 100 mvmt'])

    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Fatalities 100 mvmt'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}'
    ))

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Fatalities'])
    
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Fatalities'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}',
        visible=False
    ))

# Create buttons for toggling
buttons = [
    dict(
        label='Rate Per 100 MVMT',
        method='update',
        args=[
            {'visible': [True, True,False, False]}
        ]
    ),
    dict(
        label='Total',
        method='update',
        args=[
            {'visible': [False, False, True, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.18,
            yanchor="top"
        )
    ]
)

title = 'Traffic Fatalities, Annually'

fig.update_traces(hovertemplate='%{y}')
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.62))

pt.plot_agol(fig, export, title, indicator, plot_name)

,Geography,Year,Fatalities,Fatalities_5 Year Rolling Average,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries,Serious injuries_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
0,Sacramento Region,2014,183,NaN,0.85,NaN,773,NaN,3.61,NaN
1,Sacramento Region,2015,229,NaN,1.06,NaN,814,NaN,3.76,NaN
2,Sacramento Region,2016,271,NaN,1.23,NaN,862,NaN,3.92,NaN
3,Sacramento Region,2017,268,NaN,1.21,NaN,944,NaN,4.26,NaN
4,Sacramento Region,2018,269,244.00,1.21,1.11,1160,910.60,5.23,4.15

,Geography,Year,Fatalities,Fatalities_5 Year Rolling Average,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries,Serious injuries_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
17,California,2020,3982,3856.20,1.33,1.15,15392,15090.40,5.15,4.50
18,California,2021,4477,3980.80,1.44,1.21,18084,16055.60,5.82,4.89
19,California,2022,4537,4107.40,1.44,1.27,17916,16798.60,5.68,5.20
20,California,2023,4142,4175.00,1.30,1.32,16760,16919.00,5.27,5.32
21,California,2024,3671,4161.80,NaN,NaN,16324,16895.20,NaN,NaN

In [46]:

indicator = 'Safety_1'
plot_name = 'toggle_injury_rate'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot1 = df_mpo  .copy()
df_plot2 = df_state.copy()


df_plot1 = df_plot1.rename(columns = {'MPO'  :'Geography'})
df_plot1['Geography'] = 'Sacramento Region'
df_plot2 = df_plot2.rename(columns = {'State':'Geography'})
df_plot2['Geography'] = 'California'

df_plot = pd.concat([df_plot1, df_plot2])
df_plot = df_plot.sort_values(['Geography', 'Year'], ascending = [False, True])
df_plot = df_plot.reset_index(drop = True)

display(df_plot.head(), df_plot.tail())


color_map  = {
    'Sacramento Region': '#9DC209'
    , 'California': '#1E90FF'
}

fig=go.Figure()

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Serious injuries 100 mvm_5 Year Rolling Average'])

    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Serious injuries 100 mvm_5 Year Rolling Average'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}'
    ))

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Serious injuries_5 Year Rolling Average'])
    
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Serious injuries_5 Year Rolling Average'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}',
        visible=False
    ))

# Create buttons for toggling
buttons = [
    dict(
        label='Rate Per 100 MVMT',
        method='update',
        args=[
            {'visible': [True, True,False, False]}
        ]
    ),
    dict(
        label='Total',
        method='update',
        args=[
            {'visible': [False, False, True, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.18,
            yanchor="top"
        )
    ]
)

title = 'Traffic Serious Injuries, 5 Year Rolling Average'

fig.update_traces(hovertemplate='%{y}')
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.62))

pt.plot_agol(fig, export, title, indicator, plot_name)

,Geography,Year,Fatalities,Fatalities_5 Year Rolling Average,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries,Serious injuries_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
0,Sacramento Region,2014,183,NaN,0.85,NaN,773,NaN,3.61,NaN
1,Sacramento Region,2015,229,NaN,1.06,NaN,814,NaN,3.76,NaN
2,Sacramento Region,2016,271,NaN,1.23,NaN,862,NaN,3.92,NaN
3,Sacramento Region,2017,268,NaN,1.21,NaN,944,NaN,4.26,NaN
4,Sacramento Region,2018,269,244.00,1.21,1.11,1160,910.60,5.23,4.15

,Geography,Year,Fatalities,Fatalities_5 Year Rolling Average,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries,Serious injuries_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
17,California,2020,3982,3856.20,1.33,1.15,15392,15090.40,5.15,4.50
18,California,2021,4477,3980.80,1.44,1.21,18084,16055.60,5.82,4.89
19,California,2022,4537,4107.40,1.44,1.27,17916,16798.60,5.68,5.20
20,California,2023,4142,4175.00,1.30,1.32,16760,16919.00,5.27,5.32
21,California,2024,3671,4161.80,NaN,NaN,16324,16895.20,NaN,NaN

In [47]:

indicator = 'Safety_1'
plot_name = 'toggle_injury_rate_annual'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot1 = df_mpo  .copy()
df_plot2 = df_state.copy()


df_plot1 = df_plot1.rename(columns = {'MPO'  :'Geography'})
df_plot1['Geography'] = 'Sacramento Region'
df_plot2 = df_plot2.rename(columns = {'State':'Geography'})
df_plot2['Geography'] = 'California'

df_plot = pd.concat([df_plot1, df_plot2])
df_plot = df_plot.sort_values(['Geography', 'Year'], ascending = [False, True])
df_plot = df_plot.reset_index(drop = True)

display(df_plot.head(), df_plot.tail())


color_map  = {
    'Sacramento Region': '#9DC209'
    , 'California': '#1E90FF'
}

fig=go.Figure()

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Serious injuries 100 mvm'])

    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Serious injuries 100 mvm'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}'
    ))

for geography, color in color_map.items():
    df_cat = df_plot[df_plot['Geography'] == geography]
    df_cat=df_cat.sort_values('Year',ascending=True)
    df_cat=df_cat.dropna(subset=['Serious injuries'])
    
    fig.add_trace(go.Bar(
        x=df_cat['Year'],
        y=df_cat['Serious injuries'],
        name=geography,
        marker=dict(color=color),
        hovertemplate='%{y}',
        visible=False
    ))

# Create buttons for toggling
buttons = [
    dict(
        label='Rate Per 100 MVMT',
        method='update',
        args=[
            {'visible': [True, True,False, False]}
        ]
    ),
    dict(
        label='Total',
        method='update',
        args=[
            {'visible': [False, False, True, True]},
            {'xaxis': {'tickangle': 0}}
        ]
    )
]

# Add dropdown menu to layout
fig.update_layout(
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1,
            xanchor="right",
            y=1.18,
            yanchor="top"
        )
    ]
)

title = 'Traffic Serious Injuries, Annually'

fig.update_traces(hovertemplate='%{y}')
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.62))

pt.plot_agol(fig, export, title, indicator, plot_name)

,Geography,Year,Fatalities,Fatalities_5 Year Rolling Average,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries,Serious injuries_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
0,Sacramento Region,2014,183,NaN,0.85,NaN,773,NaN,3.61,NaN
1,Sacramento Region,2015,229,NaN,1.06,NaN,814,NaN,3.76,NaN
2,Sacramento Region,2016,271,NaN,1.23,NaN,862,NaN,3.92,NaN
3,Sacramento Region,2017,268,NaN,1.21,NaN,944,NaN,4.26,NaN
4,Sacramento Region,2018,269,244.00,1.21,1.11,1160,910.60,5.23,4.15

,Geography,Year,Fatalities,Fatalities_5 Year Rolling Average,Fatalities 100 mvmt,Fatalities 100 mvmt_5 Year Rolling Average,Serious injuries,Serious injuries_5 Year Rolling Average,Serious injuries 100 mvm,Serious injuries 100 mvm_5 Year Rolling Average
17,California,2020,3982,3856.20,1.33,1.15,15392,15090.40,5.15,4.50
18,California,2021,4477,3980.80,1.44,1.21,18084,16055.60,5.82,4.89
19,California,2022,4537,4107.40,1.44,1.27,17916,16798.60,5.68,5.20
20,California,2023,4142,4175.00,1.30,1.32,16760,16919.00,5.27,5.32
21,California,2024,3671,4161.80,NaN,NaN,16324,16895.20,NaN,NaN

***

Safety_2

***

In [ ]:

indicator = 'Safety_2'
plot_name = 'nonmotorized_fatalities'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot = df_mpo.copy()
df_plot = df_plot.dropna()

display(df_plot.head())


fig = px.bar(df_plot, y='Non motorized fatalities_5 Year Rolling Average', x='Year')
fig.update_traces(marker_color='#1E90FF')

# title = '<b>Non-Motorized Fatalities, 5 Year Rolling Average</b> <br> <sup>Sacramento Region</sup>'
title = 'Fatalities, 5 Year Rolling Average'
fig.update_yaxes(tick0=0, dtick=10, range = [0, 105])
fig.update_traces(hovertemplate='%{y}')


pt.plot_agol(fig, export, title, indicator, plot_name)

In [ ]:

indicator_name = 'Safety_2'
plot_name = 'nonmotorized_injuries'


df_mpo   = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} MPO TIMS.xlsx"      , sheet_name = 'MPO'      )
df_state = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator} Statewide TIMS.xlsx", sheet_name = 'Statewide')


df_plot = df_mpo.copy()

df_plot = df_plot.dropna()

display(df_plot.head())


fig = px.bar(df_plot, y='Non motorized serious in_5 Year Rolling Average', x='Year')
fig.update_traces(marker_color='#1E90FF')

# title = '<b>Non-Motorized Serious Injuries, 5 Year Rolling Average</b> <br> <sup>Sacramento Region</sup>'
title = 'Serious Injuries, 5 Year Rolling Average'
fig.update_yaxes(tick0=0, dtick=50, range = [0, 275])
fig.update_traces(hovertemplate='%{y}')


pt.plot_agol(fig, export, title, indicator, plot_name)

***

Safety_3

***

In [ ]:

indicator_name = 'Safety_3'
plot_name = 'ej'


df_mpo = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator_name} TIMS.xlsx", sheet_name='Region', skiprows=1)
df_mpo = df_mpo[['Year', 'Fatal', 'Serious Injury', 'Total Injury']]


df_plot = df_mpo.copy()

df_plot.columns = ['Year', 'Fatal Collisions', 'Serious Injury Collisions', 'Total Injury Collisions']
df_plot = pd.melt(df_plot, id_vars = ['Year'], var_name = 'Metric', value_name = 'Percentage')
df_plot['Percentage'] = round(df_plot['Percentage']*100, 1)

display(df_plot.head())


color_map = {
    'Fatal Collisions': '#1F45FC'
    , 'Serious Injury Collisions': '#1E90FF'
    , 'Total Injury Collisions': '#9DC209'
}

fig = px.bar(df_plot, y='Percentage', x='Year'
             , color='Metric'
             , facet_col='Metric'
             , color_discrete_map=color_map)

title = '<b>Percent of Collisions Occurring in Environmental Justice Communities</b>  <br><sup>Non-freeway collisions in 6-county Sacramento region</sup><br><br>'
fig.update_yaxes(tick0=0, dtick=10, range = [0, 102], ticksuffix='%')
fig.update_traces(hovertemplate='%{y}')
fig.update_xaxes(dtick=2)
fig['layout']['xaxis2']['title']['text']=''
fig['layout']['xaxis3']['title']['text']=''
fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))

for annotation in fig['layout']['annotations']:
    annotation['y'] = -0.1
    
pt.plot_agol(fig, export, title, indicator, plot_name)

***

Safety_4

***

In [ ]:


indicator_name = 'Safety_4'
plot_name = 'fatalities'


df_mpo = pd.read_excel(os.path.join(PATH_PLOTS/'Data'/f"{indicator_name} MPO TIMS.xlsx"), sheet_name='MPO')



df_plot = df_mpo.copy()

df_plot = df_plot.dropna()
df_plot = df_plot.sort_values(['Year', 'Category'], ascending = [False, True])

display(df_plot.head())


color_map  = {
    'Bicyclists': '#9DC209'
    , 'Pedestrians': '#1E90FF'
}


fig = px.bar(df_plot, y='Fatalities_5 Year Average', x='Year', color='Category', color_discrete_map=color_map, barmode='group')

title = 'Fatalities, 5 Year Rolling Average'
fig.update_yaxes(tick0=0, dtick=10, range = [0, 101])
fig.update_traces(hovertemplate='%{y}')
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.55))

pt.plot_agol(fig, export, title, indicator, plot_name)

In [ ]:


indicator_name = 'Safety_4'
plot_name = 'serious_injuries'


df_mpo = pd.read_excel(PATH_PLOTS/'Data'/f"{indicator_name} MPO TIMS.xlsx", sheet_name='MPO')


df_plot = df_mpo.copy()

df_plot = df_plot.dropna()
df_plot = df_plot.sort_values(['Year', 'Category'], ascending = [False, True])

display(df_plot.head())


color_map  = {
    'Bicyclists': '#9DC209'
    , 'Pedestrians': '#1E90FF'
}

fig = px.bar(df_plot, y='Serious Injuries_5 Year Average', x='Year', color='Category', color_discrete_map=color_map, barmode='group')

title = 'Serious Injuries, 5 Year Rolling Average'
fig.update_yaxes(tick0=0, dtick=20, range = [0, 181])
fig.update_traces(hovertemplate='%{y}')
fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=-0.15,xanchor="right", x=0.55))


pt.plot_agol(fig, export, title, indicator, plot_name)